# Generated by Django 4.2.10 on 2024-11-25 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
